name: bursaconnect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  fluttertoast: ^9.0.0
  image_picker: ^1.0.4
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  
  # Biometric authentication
  local_auth: ^2.1.6
  local_auth_android: ^1.0.32
  local_auth_darwin: ^1.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
