// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA81PiEYC4BVy0hG-qCShaxs0P63hcrcQc',
    appId: '1:107502416839:web:736c8362bf5d048e4d1fe2',
    messagingSenderId: '107502416839',
    projectId: 'bursaconnect',
    authDomain: 'bursaconnect.firebaseapp.com',
    storageBucket: 'bursaconnect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ67urIYy7I1JODVcOaojy_McvgBwnLZg',
    appId: '1:107502416839:android:e0ac34a87d712aec4d1fe2',
    messagingSenderId: '107502416839',
    projectId: 'bursaconnect',
    storageBucket: 'bursaconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM_RFCk2kJrWUK2r1MC8PwajZimSjwcJk',
    appId: '1:107502416839:ios:c9b9b2c72cea70c24d1fe2',
    messagingSenderId: '107502416839',
    projectId: 'bursaconnect',
    storageBucket: 'bursaconnect.firebasestorage.app',
    iosBundleId: 'com.example.bursaconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM_RFCk2kJrWUK2r1MC8PwajZimSjwcJk',
    appId: '1:107502416839:ios:c9b9b2c72cea70c24d1fe2',
    messagingSenderId: '107502416839',
    projectId: 'bursaconnect',
    storageBucket: 'bursaconnect.firebasestorage.app',
    iosBundleId: 'com.example.bursaconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA81PiEYC4BVy0hG-qCShaxs0P63hcrcQc',
    appId: '1:107502416839:web:4a793da5e2f140e44d1fe2',
    messagingSenderId: '107502416839',
    projectId: 'bursaconnect',
    authDomain: 'bursaconnect.firebaseapp.com',
    storageBucket: 'bursaconnect.firebasestorage.app',
  );

}