import 'package:bursaconnect/Admin/Screens/Bursary/bursary.dart';
import 'package:flutter/material.dart';
import 'package:bursaconnect/Admin/Screens/Bursary/BursaryDetails.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by FlutterFire CLI


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: "/bursary",
      routes: {
        "/bursary":(context) => Bursary(),
        "/bursarydetail":(context) => BursaryDetails(),
      },
      title: 'BursaConnect',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.indigo),
        useMaterial3: true,
      ),

      home: const MyHomePage(title: 'Welcome to BursaConnect'),

    );
  }
}


class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.primaryContainer,
        title: Text(widget.title),
      ),
      body: const Center(
        child: Text(
          'Firebase connected successfully 🎉',
          style: TextStyle(fontSize: 20),
        ),
      ),
    );
  }
}
