import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'Admin/Screens/Dashboard/admin_dashboard.dart';
import 'Admin/theme/theme_provider.dart';
import 'firebase_options.dart'; // This file is generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize theme provider and load saved preferences
  final themeProvider = ThemeProvider();
  await themeProvider.initializeTheme();

  runApp(
    ChangeNotifierProvider.value(value: themeProvider, child: const MyApp()),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeProvider>(
      builder: (context, themeProvider, child) {
        return MaterialApp(
          title: 'BursaConnect',
          theme: themeProvider.currentTheme,
          home: const AdminDashboard(),
          debugShowCheckedModeBanner: false,
        );
      },
    );
  }
}
