import 'package:bursaconnect/Admin/Screens/Bursary/bursary.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by FlutterFire CLI
import './Authentication/login_screen.dart';
import './Admin/Screens/Dashboard/adminDash.dart';
import './Users/Screens/Dashboard/UserDashboard.dart';
import './Authentication/signup_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      title: 'Bursary App',
      debugShowCheckedModeBanner: false,

      // 👇 Define named routes here
      initialRoute: '/login',
      routes: {
        '/login': (context) => const LoginScreen(),
        '/adminDashboard': (context) => const AdminDashboard(),
        '/userDashboard': (context) => const UserDashboard(),
      },
    );
  }
}
